name: Build

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      ## Lint
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      # pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 #v4
        with:
          version: v1.56.2

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64', 'arm64']
        os: ['darwin', 'linux', 'windows']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Display Go version
        run: go version
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -mod vendor -o ./bin/aws-s3-bucket-purger-${{ matrix.arch }}-${{ matrix.os }}