name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ['amd64', 'arm64']
        os: ['darwin', 'linux', 'windows']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: go version
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -mod vendor -o ./bin/aws-s3-bucket-purger-${{ matrix.arch }}-${{ matrix.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: aws-s3-bucket-purger-${{ matrix.arch }}-${{ matrix.os }}
          path: ./bin/aws-s3-bucket-purger-${{ matrix.arch }}-${{ matrix.os }}
          if-no-files-found: error
          retention-days: 1
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -l ./aws-s3-bucket-purger-amd64-darwin/
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          fail_on_unmatched_files: true
          files: aws-s3-bucket-purger-*/**